#!/usr/bin/env python3
"""
Memory Architecture Audit Script

Audits the 3-layer OpenClaw memory system:
- Layer 1: Workspace files (MEMORY.md, daily files)
- Layer 2: LCM (Lossless Context Management) SQLite database
- Layer 3: QMD (Quick Markdown Search) semantic index

Usage:
    python3 audit_memory.py [--fix] [--json]

Options:
    --fix    Attempt to fix minor issues (create missing daily file)
    --json   Output results as JSON
"""

import argparse
import json
import os
import sqlite3
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Configuration
WORKSPACE = Path.home() / ".openclaw" / "workspace"
MEMORY_FILE = WORKSPACE / "MEMORY.md"
DAILY_DIR = WORKSPACE / "memory" / "daily"
LCM_DB = Path.home() / ".openclaw" / "lcm.db"
QMD_INDEX = Path.home() / ".cache" / "qmd" / "index.sqlite"

def get_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def check_workspace_layer(fix=False):
    """Audit Layer 1: Workspace files"""
    issues = []
    stats = {}

    # Check MEMORY.md
    if MEMORY_FILE.exists():
        stat = MEMORY_FILE.stat()
        stats["memory_md"] = {
            "exists": True,
            "size_bytes": stat.st_size,
            "lines": sum(1 for _ in open(MEMORY_FILE, "r")),
            "modified": datetime.fromtimestamp(stat.st_mtime).isoformat()
        }
    else:
        issues.append({"severity": "critical", "issue": "MEMORY.md missing", "path": str(MEMORY_FILE)})
        stats["memory_md"] = {"exists": False}

    # Check daily directory structure
    today = datetime.now()
    today_path = DAILY_DIR / str(today.year) / f"{today.month:02d}" / f"{today.day:02d}.md"

    if DAILY_DIR.exists():
        daily_files = list(DAILY_DIR.glob("**/*.md"))
        stats["daily_files"] = {
            "directory_exists": True,
            "total_files": len(daily_files),
            "today_exists": today_path.exists()
        }

        if not today_path.exists():
            if fix:
                today_path.parent.mkdir(parents=True, exist_ok=True)
                with open(today_path, "w") as f:
                    f.write(f"# {today.strftime('%Y-%m-%d')} — Daily Notes\n\n*Auto-generated by memory-architect audit.*\n")
                issues.append({"severity": "fixed", "issue": "Created missing daily file", "path": str(today_path)})
            else:
                issues.append({"severity": "warning", "issue": "Today's daily file missing", "path": str(today_path)})
    else:
        issues.append({"severity": "critical", "issue": "Daily directory missing", "path": str(DAILY_DIR)})
        stats["daily_files"] = {"directory_exists": False}

    # Check supporting files
    supporting = ["AGENTS.md", "SOUL.md", "USER.md", "HEARTBEAT.md", "TODO.md"]
    stats["supporting_files"] = {}
    for fname in supporting:
        fpath = WORKSPACE / fname
        stats["supporting_files"][fname] = fpath.exists()

    return {"stats": stats, "issues": issues}

def check_lcm_layer():
    """Audit Layer 2: LCM database"""
    issues = []
    stats = {}

    if LCM_DB.exists():
        try:
            conn = sqlite3.connect(str(LCM_DB))
            cursor = conn.cursor()

            # Check schema
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
            tables = {row[0] for row in cursor.fetchall()}
            # Core required tables (schema may vary by version)
            required = {"conversations", "messages", "summaries"}
            missing = required - tables

            if missing:
                issues.append({"severity": "critical", "issue": f"LCM core tables missing: {missing}"})

            # Get counts
            if "messages" in tables:
                cursor.execute("SELECT COUNT(*) FROM messages")
                stats["messages"] = cursor.fetchone()[0]

            if "summaries" in tables:
                cursor.execute("SELECT COUNT(*) FROM summaries")
                stats["summaries"] = cursor.fetchone()[0]

            if "conversations" in tables:
                cursor.execute("SELECT COUNT(*) FROM conversations")
                stats["conversations"] = cursor.fetchone()[0]

            # Get freshness
            if "messages" in tables:
                cursor.execute("SELECT created_at FROM messages ORDER BY created_at DESC LIMIT 1")
                row = cursor.fetchone()
                stats["last_message"] = row[0] if row else None

            if "summaries" in tables:
                cursor.execute("SELECT created_at FROM summaries ORDER BY created_at DESC LIMIT 1")
                row = cursor.fetchone()
                stats["last_summary"] = row[0] if row else None

            conn.close()
            stats["db_exists"] = True
            stats["db_size_mb"] = round(LCM_DB.stat().st_size / (1024 * 1024), 2)

        except sqlite3.Error as e:
            issues.append({"severity": "critical", "issue": f"LCM database error: {e}"})
            stats["db_exists"] = True
            stats["error"] = str(e)
    else:
        issues.append({"severity": "critical", "issue": "LCM database missing"})
        stats["db_exists"] = False

    return {"stats": stats, "issues": issues}

def check_qmd_layer():
    """Audit Layer 3: QMD semantic index"""
    issues = []
    stats = {}

    # Check if qmd is installed
    try:
        result = subprocess.run(["which", "qmd"], capture_output=True, text=True)
        if result.returncode == 0:
            stats["qmd_path"] = result.stdout.strip()
            stats["installed"] = True
        else:
            stats["installed"] = False
            issues.append({"severity": "warning", "issue": "QMD not found in PATH"})
    except Exception as e:
        stats["installed"] = False
        issues.append({"severity": "warning", "issue": f"QMD check failed: {e}"})

    # Check index file
    if QMD_INDEX.exists():
        try:
            conn = sqlite3.connect(str(QMD_INDEX))
            cursor = conn.cursor()

            # Try to get document count (schema may vary)
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
            tables = {row[0] for row in cursor.fetchall()}

            stats["index_exists"] = True
            stats["index_size_mb"] = round(QMD_INDEX.stat().st_size / (1024 * 1024), 2)
            stats["tables"] = list(tables)

            conn.close()
        except sqlite3.Error as e:
            issues.append({"severity": "warning", "issue": f"QMD index read error: {e}"})
            stats["index_exists"] = True
            stats["error"] = str(e)
    else:
        stats["index_exists"] = False
        issues.append({"severity": "info", "issue": "QMD index not found (may not be initialized)"})

    # Check MCP server
    try:
        result = subprocess.run(
            ["curl", "-s", "--connect-timeout", "2", "http://127.0.0.1:8181/health"],
            capture_output=True, text=True
        )
        if result.returncode == 0 and "ok" in result.stdout.lower():
            stats["mcp_running"] = True
            try:
                health = json.loads(result.stdout)
                stats["mcp_uptime"] = health.get("uptime", "unknown")
            except:
                pass
        else:
            stats["mcp_running"] = False
    except Exception:
        stats["mcp_running"] = False

    return {"stats": stats, "issues": issues}

def main():
    parser = argparse.ArgumentParser(description="Audit OpenClaw memory architecture")
    parser.add_argument("--fix", action="store_true", help="Attempt to fix minor issues")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    results = {
        "timestamp": get_timestamp(),
        "workspace": str(WORKSPACE),
        "layers": {
            "workspace": check_workspace_layer(fix=args.fix),
            "lcm": check_lcm_layer(),
            "qmd": check_qmd_layer()
        }
    }

    # Calculate overall health
    all_issues = []
    for layer in results["layers"].values():
        all_issues.extend(layer.get("issues", []))

    critical = sum(1 for i in all_issues if i.get("severity") == "critical")
    warnings = sum(1 for i in all_issues if i.get("severity") == "warning")
    fixed = sum(1 for i in all_issues if i.get("severity") == "fixed")

    health_score = max(0, 100 - (critical * 25) - (warnings * 5))
    results["health"] = {
        "score": health_score,
        "status": "healthy" if health_score >= 90 else "degraded" if health_score >= 70 else "critical",
        "critical_issues": critical,
        "warnings": warnings,
        "fixed": fixed
    }

    if args.json:
        print(json.dumps(results, indent=2))
    else:
        print(f"\n{'='*60}")
        print(f"Memory Architecture Audit — {results['timestamp']}")
        print(f"{'='*60}\n")

        print(f"Overall Health: {health_score}% ({results['health']['status']})")
        print(f"  Critical: {critical} | Warnings: {warnings} | Fixed: {fixed}\n")

        # Layer 1
        ws = results["layers"]["workspace"]
        print("Layer 1: Workspace Files")
        if ws["stats"].get("memory_md", {}).get("exists"):
            mm = ws["stats"]["memory_md"]
            print(f"  ✅ MEMORY.md: {mm['lines']} lines, {mm['size_bytes']} bytes")
        else:
            print("  ❌ MEMORY.md: MISSING")

        df = ws["stats"].get("daily_files", {})
        if df.get("directory_exists"):
            status = "✅" if df.get("today_exists") else "⚠️ "
            print(f"  {status} Daily files: {df.get('total_files', 0)} files")
        else:
            print("  ❌ Daily directory: MISSING")

        # Layer 2
        lcm = results["layers"]["lcm"]
        print("\nLayer 2: LCM (Lossless Context Management)")
        if lcm["stats"].get("db_exists"):
            print(f"  ✅ Database: {lcm['stats'].get('db_size_mb', 0)} MB")
            print(f"     Messages: {lcm['stats'].get('messages', 0)}")
            print(f"     Summaries: {lcm['stats'].get('summaries', 0)}")
            print(f"     Last message: {lcm['stats'].get('last_message', 'N/A')}")
        else:
            print("  ❌ Database: MISSING")

        # Layer 3
        qmd = results["layers"]["qmd"]
        print("\nLayer 3: QMD (Semantic Search)")
        if qmd["stats"].get("installed"):
            print(f"  ✅ QMD: {qmd['stats'].get('qmd_path', 'installed')}")
            if qmd["stats"].get("index_exists"):
                print(f"     Index: {qmd['stats'].get('index_size_mb', 0)} MB")
            mcp = "running" if qmd["stats"].get("mcp_running") else "stopped"
            print(f"     MCP: {mcp}")
        else:
            print("  ⚠️  QMD: Not installed")

        # Issues
        if all_issues:
            print(f"\n{'─'*60}")
            print("Issues:")
            for issue in all_issues:
                sev = issue.get("severity", "info")
                icon = "❌" if sev == "critical" else "⚠️ " if sev == "warning" else "✅" if sev == "fixed" else "ℹ️ "
                print(f"  {icon} [{sev.upper()}] {issue.get('issue', 'Unknown')}")
                if issue.get("path"):
                    print(f"      {issue['path']}")

        print(f"\n{'='*60}\n")

    return 0 if health_score >= 70 else 1

if __name__ == "__main__":
    sys.exit(main())
